version: "3"
services:
  node-server:
    build: # ตำแหน่ง dockerfile
      context: ./backend/V0.2
      args:
        NODE_ENV: development
    container_name: node-container
    env_file: 
      - ./.env
    ports:
      - "${PORT}:${PORT}" # outside:inside
      - "9229:9229"
    volumes:
      - ./frontend/build:/usr/src/app/frontend_build
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    command: npm run dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  postgres:
    image: postgres:15
    container_name: postgres_container
    env_file: 
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
