version: "3"
services:
  node-server:
    build: .
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/usr/src/Wealthtrack-app/src
    depends_on: ["mongodb"]
  mongodb:
    image: mongo
    container_name: mongodb_container
    env_file: .env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: