openapi: 3.0.0
info:
  title: WealthTack API
  description: API for user registration and check password.
  version: "0.2"
servers:
  - url: "http://localhost:3000/api/v0.2"
    description: Development server
paths:
  /:
    get:
      tags:
        - "Connection"
      summary: API Root (v0.2)
      description: Returns a welcome message to confirm API connectivity.
      responses:
        "200":
          description: Successful response with a welcome message in JSON format.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
              example:
                status_code: 200
                message: "You are connected to the /api/v0.2/"
                data: null

  /api:
    get:
      tags:
        - "Connection"
      summary: API Root (General)
      description: Returns a welcome message to confirm API connectivity.
      servers:
        - url: "http://localhost:3000"
      responses:
        "200":
          description: Successful response with a welcome message in JSON format.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
              example:
                status_code: 200
                message: "You are connected to the /api, running in Environment: development"
                data: null

  /health:
    get:
      tags:
        - "Connection"
      summary: Health check
      description: Returns a plain text string to confirm the API is running.
      servers:
        - url: "http://localhost:3000"
      responses:
        "200":
          description: Healthy response in plain text.
          content:
            text/plain:
              schema:
                type: string
                example: "OK"
  /users:
    post:
      tags:
        - "User"
      summary: Register a new user
      description: Creates a new user with the provided information.
      requestBody:
        description: User registration data.
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - national_id
                - username
                - email
                - password
                - confirm_password
              properties:
                national_id:
                  type: string
                  description: National ID (13 numeric characters).
                  example: "1234567890123"
                username:
                  type: string
                  description: Username (alphanumeric, no special characters).
                  example: "johndoe"
                email:
                  type: string
                  format: email
                  description: Valid email address.
                  example: "johndoe@example.com"
                password:
                  type: string
                  format: password
                  description: Password (minimum 8 characters).
                  example: "securePassword123"
                confirm_password:
                  type: string
                  format: password
                  description: Password confirmation (must match password).
                  example: "securePassword123"
      responses:
        "201":
          description: User created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 201
                  message:
                    type: string
                    example: "User created successfully"
                  data:
                    type: object
                    properties:
                      national_id:
                        type: string
                        example: "1234567890123"
                      email:
                        type: string
                        example: "johndoe@example.com"
        "400":
          description: Bad request due to missing required fields, invalid email address, or password mismatch.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "Missing required field: username"
        "409":
          description: Conflict due to duplicate user.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 409
                  message:
                    type: string
                    example: "national_id or email are already taken"

  /users/check:
    post:
      tags:
        - "User"
      summary: Check user password (Development Mode Only)
      description: Validates user's email and password.
      requestBody:
        description: User login data.
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address.
                  example: "johndoe@example.com"
                password:
                  type: string
                  format: password
                  description: User's password.
                  example: "securePassword123"
      responses:
        "200":
          description: Password check successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "Password check successful"
                  data:
                    type: boolean
                    example: true
        "400":
          description: Bad request due to missing required fields or invalid email address.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "Missing required field: email"
        "401":
          description: Unauthorized due to incorrect password.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 401
                  message:
                    type: string
                    example: "Invalid email or password"

  /users/{national_id}:
    get:
      tags:
        - "User"
      summary: Get user by National ID (NOT Implemented)
      description: Retrieves user information based on National ID.
      parameters:
        - in: path
          name: national_id
          schema:
            type: string
            length: 13
          required: true
          description: National ID of the user.
      responses:
        "200":
          description: User retrieved successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
        "400":
          description: Bad request due to invalid National ID.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: User not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    patch:
      tags:
        - "User"
      summary: Update user by National ID (NOT Implemented)
      description: Updates user information.
      parameters:
        - in: path
          name: national_id
          schema:
            type: string
            length: 13
          required: true
          description: National ID of the user.
      requestBody:
        description: Fields to update.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: New username.
                email:
                  type: string
                  format: email
                  description: New email address.
                password:
                  type: string
                  format: password
                  description: New password.
      responses:
        "200":
          description: User updated successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
        "400":
          description: Bad request due to invalid input.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: User not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      tags:
        - "User"
      summary: Delete user by National ID (NOT Implemented)
      description: Deletes a user from the system.
      parameters:
        - in: path
          name: national_id
          schema:
            type: string
            length: 13
          required: true
          description: National ID of the user.
      responses:
        "204":
          description: User deleted successfully. No content returned.
        "400":
          description: Bad request due to invalid National ID.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: User not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /slip:
    post:
      summary: Extract slip data (NOT available)
      tags:
        - Slip
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SlipDataRequest"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SlipDataResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "429":
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /slip/quota:
    get:
      summary: Get quota information
      tags:
        - Slip
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuotaResponse"
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    User:
      type: object
      properties:
        national_id:
          type: string
          description: National ID of the user (13 characters).
          example: "1234567890123"
        username:
          type: string
          description: Username of the user.
          example: "johndoe"
        email:
          type: string
          format: email
          description: Email address of the user.
          example: "johndoe@example.com"
        password:
          type: string
          format: password
          description: Password (this is client-side input only, hashed on the server side).
          example: "securePassword123"
        confirm_password:
          type: string
          format: password
          description: Password confirmation (must match the password).
          example: "securePassword123"
        role:
          type: string
          description: Role assigned to the user (auto-assigned, not client-specified).
          example: "user"
        member_since:
          type: string
          format: date-time
          description: Date and time when the user was registered (auto-assigned).
          example: "2024-09-09T10:25:22.650Z"
      required:
        - national_id
        - username
        - email
        - password
        - confirm_password

    Response:
      type: object
      properties:
        status_code:
          type: integer
          example: 200
        message:
          type: string
          example: "Operation successful"
        data:
          type: object
          description: Additional data returned with the response.

    ErrorResponse:
      type: object
      properties:
        status_code:
          type: integer
          example: 401
        message:
          type: string
          description: Error message detailing the cause of the error.
          example: "Invalid input data"

    QuotaResponse:
      type: object
      properties:
        status_code:
          type: integer
          example: 200
        message:
          type: string
          example: "get quota information success"
        data:
          type: object
          properties:
            application:
              type: string
              example: "EasySlip Developer"
            usedQuota:
              type: number
              example: 16
            maxQuota:
              type: number
              example: 35000
            remainingQuota:
              type: number
              example: 34984
            expiredAt:
              type: string
              format: date-time
              example: "2024-02-22T18:47:34+07:00"
            currentCredit:
              type: number
              example: 1000

    SlipDataRequest:
      type: object
      required:
        - base64Image
      properties:
        base64Image:
          type: string
          description: Base64 encoded image data

    SlipDataResponse:
      type: object
      properties:
        status_code:
          type: integer
          example: 200
        message:
          type: string
          example: "Slip verification success"
        data:
          type: object
          properties:
            payload:
              type: string
              example: "00000000000000000000000000000000000000000000000000000000000"
            transRef:
              type: string
              example: "68370160657749I376388B35"
            date:
              type: string
              format: date-time
              example: "2023-01-01T00:00:00+07:00"
            countryCode:
              type: string
              example: "TH"
            amount:
              type: object
              properties:
                amount:
                  type: number
                  example: 1000
                local:
                  type: object
                  properties:
                    amount:
                      type: number
                      example: 0
                    currency:
                      type: string
                      example: ""
            fee:
              type: number
              example: 0
            ref1:
              type: string
              example: ""
            ref2:
              type: string
              example: ""
            ref3:
              type: string
              example: ""
            sender:
              type: object
              properties:
                bank:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "001"
                    name:
                      type: string
                      example: "กสิกรไทย"
                    short:
                      type: string
                      example: "KBANK"
                account:
                  type: object
                  properties:
                    name:
                      type: object
                      properties:
                        th:
                          type: string
                          example: "นาย อีซี่ สลิป"
                        en:
                          type: string
                          example: "MR. EASY SLIP"
                    bank:
                      type: object
                      properties:
                        type:
                          type: string
                          enum:
                            - BANKAC
                            - TOKEN
                            - DUMMY
                          example: "BANKAC"
                        account:
                          type: string
                          example: "1234xxxx5678"
            receiver:
              type: object
              properties:
                bank:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "030"
                    name:
                      type: string
                      example: "ธนาคารออมสิน"
                    short:
                      type: string
                      example: "GSB"
                account:
                  type: object
                  properties:
                    name:
                      type: object
                      properties:
                        th:
                          type: string
                          example: "นาย อีซี่ สลิป"
                    bank:
                      type: object
                      properties:
                        type:
                          type: string
                          enum:
                            - BANKAC
                            - TOKEN
                            - DUMMY
                          example: "BANKAC"
                        account:
                          type: string
                          example: "12xxxx3456"
                    proxy:
                      type: object
                      properties:
                        type:
                          type: string
                          enum:
                            - NATID
                            - MSISDN
                            - EWALLETID
                            - EMAIL
                            - BILLERID
                          example: "EWALLETID"
                        account:
                          type: string
                          example: "123xxxxxxxx4567"
