# This is a basic workflow that is manually triggered

name: Deploy to staging server

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    types:
      - closed
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_deploy:
    if: github.event.pull_request.merged == true && github.actor == ${{ secrets.TRIGGERS_USERNAME }}
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Repository # action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
          uses: actions/checkout@v4

        - name: Setup SSH Connection
          uses: webfactory/ssh-agent@v0.9.0
          with:
                ssh-private-key: ${{ secrets.GITHUB_ACTION_SSH_PRIVATE_KEY }}

        - name: SSH and Build_Deploy
              run: |
                ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_SERVER_USERNAME }}@${{ secrets.STAGING_SERVERS_IP }} <<'EOF'
                cd ~/WealthTracking
                ./deploy.sh
                EOF

         
