name: Deploy to staging server

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build_deploy:
    if: github.event.pull_request.merged == true && github.actor == 'SawatKia'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Connection
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GH_ACTION_SSH_PRIVATE_KEY }}

      - name: SSH and Build_Deploy
        if: ${{ env.continue == 'true' }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_SERVER_USERNAME }}@${{ secrets.STAGING_SERVERS_IP }} <<'EOF'
          cd ~/WealthTracking
          ./deploy.sh
          EOF

      - name: Notify Discord
        if: ${{ env.continue == 'true' }}
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GUTHIB_TOKENS }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Bob"
          avatar-url: "https://avatars.githubusercontent.com/u/88827707?v=4"
          title: "Deployment to ${{ github.workflow }} Server: ${{ github.action_status }}"
          description: "Automated deployment to the ${{ github.workflow }} server triggered by ${{ github.event_name }}. Status: ${{ github.action_status }}. Please verify the deployment and report any issues to the Dev team."
          include-details: "true"
          color-success: "#1ced11"
          color-failure: "#eb4034"
          color-cancelled: "#edcc11"
