name: Deploy to staging server

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build_deploy:
    if: github.event.pull_request.merged == true && github.actor == 'SawatKia'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Connection
        run: |
          echo "Setting up SSH connection..."
          mkdir -p ~/.ssh
          echo "${{ secrets.GH_ACTION_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          echo "SSH setup complete. Testing connection..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.STAGING_SERVER_USERNAME }}@${{ secrets.STAGING_SERVERS_IP }} "echo 'SSH connection successful!'"

      - name: Build and Deploy on Server
        run: |
          echo "Starting build and deployment process on the server..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.STAGING_SERVER_USERNAME }}@${{ secrets.STAGING_SERVERS_IP }} << 'EOF'
            echo "the current user: $(whoami)"
            echo "the current directory: $(pwd)"
            echo "Navigating to project directory..."
            cd ~/WealthTracking || exit 1
            echo "Pulling git repo..."
            git pull origin main --recurse-submodules
            echo "Executing deploy script..."
            ./deploy.sh || exit 1
            echo "Deployment completed successfully."
          EOF

      - name: Notify Discord
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GUTHIB_TOKENS }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Bob"
          avatar-url: "https://avatars.githubusercontent.com/u/88827707?v=4"
          title: "Deployment to ${{ github.workflow }} Server: ${{ github.action_status }}"
          description: "Automated deployment to the ${{ github.workflow }} server triggered by ${{ github.event_name }}. Status: ${{ github.action_status }}. Please verify the deployment and report any issues to the Dev team."
          include-details: "true"
          color-success: "#1ced11"
          color-failure: "#eb4034"
          color-cancelled: "#edcc11"

      - name: Delete SSH Key
        run: |
          echo "Cleaning up SSH key..."
          rm -f ~/.ssh/id_rsa
          echo "SSH key deleted."
