name: Deploy to staging server

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build_deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Server Port Connectivity
        run: |
          nc -zv ${{ secrets.STAGING_SERVERS_IP }} 22 80 443

      - name: Setup SSH Connection
        run: |
          echo "Setting up SSH connection..."
          mkdir -p ~/.ssh
          echo "${{ secrets.GH_ACTION_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          echo "SSH setup complete. Testing connection..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.STAGING_SERVER_USERNAME }}@${{ secrets.STAGING_SERVERS_IP }} "echo 'SSH connection successful!'"

      - name: Build and Deploy on Server
        id: deploy
        run: |
          set -o pipefail
          echo "Starting build and deployment process on the server..."
          output=$(ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.STAGING_SERVER_USERNAME }}@${{ secrets.STAGING_SERVERS_IP }} << 'EOF'
            echo "Navigating to project directory..."
            cd ~/WealthTracking || { echo "Failed to navigate to project directory"; exit 1; }

            echo "Granting permissions to bash scripts..."
            chmod +x deploy.sh installing.sh start_server.sh update-nginx-blacklist.sh internet.sh || { echo "Failed to grant permissions"; exit 1; }

            echo "Executing deploy script..."
            ./deploy.sh ${{ secrets.STAGING_SERVERS_IP }} || { echo "Deployment script failed"; exit 1; }

            echo "Deployment completed successfully."
          EOF
          )
          exit_code=$?
          echo "DEPLOY_OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$output" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          exit $exit_code

      - name: Notify Discord on Success
        if: steps.deploy.outcome == 'success'
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: "🚀 Workflow Notifier"
          avatar-url: "https://avatars.githubusercontent.com/u/88827707?v=4"
          title: "✨ **${{ github.workflow }}** ran **${{ job.status }}**"
          description: |
            🔔 **Triggered Event**: *`${{ github.event_name }}`* initiated by **@`${{ github.actor }}`**
            🔄 Associated **Commit**: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}>
            📦 **Job** ran: `${{ github.job }}`
            ✅ **Deployment Status**: Success 🎉
          include-details: "true"
          color-success: "#28a745" # Green for running the job success
          color-failure: "#8a0d04" # Dark Red for running the job failure
          color-cancelled: "#ffc107" # Yellow for running the job cancelled

      - name: Notify Discord on Failure
        if: steps.deploy.outcome == 'failure'
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: "🚀 Workflow Notifier"
          avatar-url: "https://avatars.githubusercontent.com/u/88827707?v=4"
          title: "❌ **${{ github.workflow }}** failed"
          description: |
            🔔 **Triggered Event**: *`${{ github.event_name }}`* initiated by **@`${{ github.actor }}`**
            🔄 Associated **Commit**: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}>
            📦 **Job** ran: `${{ github.job }}`
            ❌ **Deployment Status**: Failed 🚨

            **Failure Reason:**  
            ```
            ${{ env.DEPLOY_OUTPUT }}
            ```
            Please check the logs for more details.
          include-details: "true"
          color-success: "#d73a49" # Green for running the job success
          color-failure: "#8a0d04" # Dark Red for running the job failure
          color-cancelled: "#ffc107" # Yellow for running the job cancelled

      - name: Delete SSH Key
        if: always()
        run: |
          echo "Cleaning up SSH key..."
          rm -f ~/.ssh/id_rsa
          echo "SSH key deleted."
